name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Build
      run: |
        go build -o main.exe -v ./main.go
    - name: Create a new directory and copy files
      run: |
        mkdir -p alac
        cp config.yaml.example alac/
        cp dev.env.example alac/
        cp README.md alac/
        cp README-CN.md alac/
        cp main.exe alac/
    - name: Upload apple-music-downloader
      uses: actions/upload-artifact@v4
      with:
        name: apple-music-downloader-windows
        path: alac/*

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Build
      run: |
        go build -o main -v ./main.go
    - name: Create a new directory and copy files
      run: |
        mkdir -p alac
        cp config.yaml.example alac/
        cp dev.env.example alac/
        cp README.md alac/
        cp README-CN.md alac/
        cp main alac/
    - name: Upload apple-music-downloader
      uses: actions/upload-artifact@v4
      with:
        name: apple-music-downloader-linux
        path: alac/*

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Build
      run: |
        go build -o main -v ./main.go
    - name: Create a new directory and copy files
      run: |
        mkdir -p alac
        cp config.yaml.example alac/
        cp dev.env.example alac/
        cp README.md alac/
        cp README-CN.md alac/
        cp main alac/
    - name: Upload apple-music-downloader
      uses: actions/upload-artifact@v4
      with:
        name: apple-music-downloader-macos
        path: alac/*
